/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital.GUI.Mantenimientos;

import Hospital.Entities.Camas;
import java.io.*;
import javax.swing.JOptionPane;


/**
 *
 * @author IVAN
 */
public class FrmCamas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCamas
     */
    private boolean esNuevo = false;
    public FrmCamas() {
        initComponents();
        CargarCombos();
        HabilitarBotones(true, true, true, false, false, true);
        HabilitarControles(false);
        limpiar();

        CargarLista();

        esNuevo = false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroCama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cboCategoria = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboEstado = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCamas = new javax.swing.JList();

        setResizable(true);
        setTitle("Mantenimiento De Camas");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento"));
        jPanel2.setLayout(new java.awt.GridLayout(1, 5));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Cama"));
        jPanel3.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Numero Cama:");
        jPanel3.add(jLabel1);
        jPanel3.add(txtNumeroCama);

        jLabel3.setText("Categoria :");
        jPanel3.add(jLabel3);

        jPanel3.add(cboCategoria);

        jLabel4.setText("Precio :");
        jPanel3.add(jLabel4);
        jPanel3.add(txtPrecio);

        jLabel5.setText("Estado");
        jPanel3.add(jLabel5);

        jPanel3.add(cboEstado);

        lstCamas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCamas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCamasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCamas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void leerdatosdesdetxt() {
        try{
        Camas c = new Camas();
        FileReader fr = null;
        fr = new FileReader("C:\\Users\\IVAN\\Documents\\NetBeansProjects\\Program\\src\\BD\\Camas.txt");
            BufferedReader b = new BufferedReader(fr);
            String cadena = "";
            Camas.lista.clear();
            
            while( (cadena =  b.readLine()) != null){ 
              String[] datos =   cadena.split("\\|");    
              c = new Camas();
              c.setNumero(Integer.parseInt(datos[0]));
              
              c.setCategoria(Integer.parseInt(datos[1]));                                          
              c.setPrecio(Double.parseDouble(datos[2]));                            
              c.setEstado(Integer.parseInt(datos[3]));
              
              c.Insertar(c);
              
            }
            
          
            b.close();
        }catch(FileNotFoundException ex )
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }catch(IOException ioexception){
            JOptionPane.showMessageDialog(null, ioexception.getMessage());
        }
        
    }
    void CargarLista(){                      
        try{
            
            leerdatosdesdetxt();
            cargarDatos();
                                                      
        }catch(Exception ex)
        {
        
        }
                         
    }
    void cargarDatos(){
         String[] datos = new String[Camas.lista.size()];
        int x = 0;
        for(Camas registro: Camas.lista){            
            datos[x] = String.valueOf(registro.getNumero());
            x++;
        }
 
        this.lstCamas.setListData(datos);
    }
    void CargarCombos(){
        this.cboCategoria.addItem("Economico");
        this.cboCategoria.addItem("Ejecutivo");
        this.cboEstado.addItem("Libre");
        this.cboEstado.addItem("Ocupado");
    }
    void HabilitarControles(boolean valor){
        this.txtNumeroCama.setEnabled(valor);
        this.txtPrecio.setEnabled(valor);
        this.cboCategoria.setEnabled(valor);
        this.cboEstado.setEnabled(valor);
    }
    void HabilitarBotones(boolean nuevo, boolean editar, boolean eliminar, 
                          boolean guardar, boolean cancelar, boolean salir ){
        this.btnNuevo.setEnabled(nuevo);
        this.btnEditar.setEnabled(editar);
        this.btnEliminar.setEnabled(eliminar);
        this.btnGuardar.setEnabled(guardar);
        this.btnCancelar.setEnabled(cancelar);
        this.btnSalir.setEnabled(salir);
    }
    
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

         HabilitarBotones(false, false, false, true, true, false);
         HabilitarControles(true);
         limpiar();
         this.cboEstado.setEnabled(false);

        esNuevo = true;
    }//GEN-LAST:event_btnNuevoActionPerformed
    void limpiar(){
        this.txtNumeroCama.setText("");
        this.txtPrecio.setText("");
        this.cboCategoria.setSelectedIndex(0);
        this.cboEstado.setSelectedIndex(0);
    }
    void cancelar(){
        HabilitarControles(false);
        HabilitarBotones(true, true, true, false, false, true);
        limpiar();
        CargarLista();
        esNuevo = false;
    }
    void mensaje(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje, "Sistema", JOptionPane.OK_OPTION);
    }
    boolean Validar(){
        if(txtNumeroCama.getText().equals("")){
            mensaje("Ingresar numero de cama");
            return false;
        }
        if(txtPrecio.getText().equals("")){
            mensaje("Ingresar Precio");
            return false;
        }
        if(Double.parseDouble(txtPrecio.getText()) <= 0  )
        {
            mensaje("Ingresar valor mayor a cero");
            return false;
        }
        
        return true;
    }
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        HabilitarBotones(false, false, false, true, true, false);
        HabilitarControles(true);
        //        HabilitarControles(true);
//        HabilitarBotones(false);
//        this.lstPaciente.setEnabled(false);
        esNuevo = false;
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Camas c = new Camas();
        c.setNumero(Integer.parseInt(txtNumeroCama.getText()));
        c.Eliminar(c);
        cancelar();
        Exportarafichero();
    }//GEN-LAST:event_btnEliminarActionPerformed
    private void Exportarafichero(){
        FileWriter fw = null;
        PrintWriter pw = null;
        try{
         fw = new FileWriter("C:\\Users\\IVAN\\Documents\\NetBeansProjects\\Program\\src\\BD\\Camas.txt");                  
          pw = new PrintWriter(fw);
          
         for(int x = 0 ; x < Camas.lista.size(); x++){
             Camas fila =  Camas.lista.get(x);
              String linea =  fila.getNumero() +"|" + fila.getCategoria() +"|" 
                            + fila.getPrecio() +"|" + fila.getEstado() ;
              pw.println(linea);
         }
        }catch(Exception ex){
         ex.printStackTrace();
        }finally{
            try{
                if(fw != null){
                    fw.close();
                }
            }catch(Exception ex2){
                ex2.printStackTrace();
            }
         }
            
        }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
          if (!Validar()) {
            return;
          }
          Camas c = new Camas();
          
          c.setNumero(Integer.parseInt(this.txtNumeroCama.getText()));
          c.setEstado(this.cboCategoria.getSelectedIndex());
          c.setPrecio(Double.parseDouble(this.txtPrecio.getText()));
          c.setCategoria(this.cboCategoria.getSelectedIndex());
//
        if (esNuevo) {          
               c.Insertar(c);
               mensaje("Registro Insertado");                                  
        } else {
            c.Actualizar(c);
            JOptionPane.showMessageDialog(null, "Registro actualizado");
        }
           
            Exportarafichero();
             cancelar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lstCamasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCamasValueChanged
        if(this.lstCamas.getSelectedValue() != null){
            int indice = lstCamas.getSelectedIndex();
            Camas registro =  Camas.lista.get(indice);
            txtNumeroCama.setText(String.valueOf(registro.getNumero())); 
            txtPrecio.setText(String.valueOf(registro.getPrecio()));
            cboCategoria.setSelectedIndex(registro.getCategoria());
            cboEstado.setSelectedIndex(registro.getEstado());
        }
    }//GEN-LAST:event_lstCamasValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboCategoria;
    private javax.swing.JComboBox cboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstCamas;
    private javax.swing.JTextField txtNumeroCama;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
