/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital.GUI.Mantenimientos;
import Hospital.Data.EmpleadoData;
import Hospital.Data.EmpleadoTabla;
import Hospital.Data.ListaData;
import Hospital.Data.PacienteData;
import Hospital.Entities.Camas;
import Hospital.Entities.Empleado;
import Hospital.Entities.Paciente;
import java.io.*;
import java.util.Vector;
import javax.swing.*;
import javax.swing.event.ListDataListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author IVAN
 */
public class FrmPaciente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPaciente
     */
    Paciente p;
    ListModel<String> lista;
    public FrmPaciente() {
        initComponents();
            
        CargarLista();                
//        this.lstPaciente = new JList(datos);
        HabilitarBotones(true);
        HabilitarControles(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPaciente = new javax.swing.JList();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento"));
        jPanel2.setLayout(new java.awt.GridLayout(1, 5));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setText("codigo :");
        jPanel1.add(jLabel1);
        jPanel1.add(txtCodigo);

        jLabel2.setText("Nombres :");
        jPanel1.add(jLabel2);
        jPanel1.add(txtNombres);

        jLabel3.setText("Apellidos .");
        jPanel1.add(jLabel3);
        jPanel1.add(txtApellidos);

        jLabel4.setText("Telefono :");
        jPanel1.add(jLabel4);
        jPanel1.add(txtTelefono);

        jLabel5.setText("Dni :");
        jPanel1.add(jLabel5);
        jPanel1.add(txtDni);

        lstPaciente.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPacienteValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPaciente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void HabilitarBotones(boolean valor){
        this.btnNuevo.setEnabled(valor);
        this.btnEditar.setEnabled(valor);
        this.btnEliminar.setEnabled(valor);
        this.btnGuardar.setEnabled(!valor);
        this.btnCancelar.setEnabled(!valor);
        this.btnSalir.setEnabled(valor);
    }
    private void HabilitarControles(boolean valor){
        this.txtCodigo.setEnabled(false);
        this.txtNombres.setEnabled(valor);
        this.txtApellidos.setEnabled(valor);
        
        this.txtTelefono.setEnabled(valor);
        this.txtDni.setEnabled(valor);
        
    }
    boolean esGrabar = false;
    private void CrearColumnas(){
        
    }
    private void limpiar(){
        this.txtCodigo.setText("");
        this.txtNombres.setText("");
        this.txtApellidos.setText("");
        this.txtDni.setText("");
        this.txtTelefono.setText("");
    }
    void leerdatosdesdetxt()  {
        try{
        Paciente c;
        FileReader fr = null;
        fr = new FileReader("C:\\Users\\IVAN\\Documents\\NetBeansProjects\\Program\\src\\BD\\Pacientes.txt");
            BufferedReader b = new BufferedReader(fr);
            String cadena = "";
            Paciente.lista.clear();
            while( (cadena =  b.readLine()) != null){ 
              String[] datos =   cadena.split("\\|");    
              p = new Paciente();
             
              p.setCodigo(Integer.parseInt(datos[0]));
              p.setApelidos(datos[1]);
              p.setNombres(datos[2]);
              p.setTelefono(datos[3]);
              p.setDni(datos[4]);
              p.Insertar(p);
              
            }
            
          
            b.close();
             }catch(FileNotFoundException ex )
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }catch(IOException ioexception){
            JOptionPane.showMessageDialog(null, ioexception.getMessage());
        }
    }
     void cargarDatos(){
         String[] datos = new String[Paciente.lista.size()];
        int x = 0;
        for(Paciente registro: Paciente.lista){            
            datos[x] = String.valueOf(registro.getCodigo());
            x++;
        }
 
        this.lstPaciente.setListData(datos);
    }
     void CargarLista(){                      
        try{
            
            leerdatosdesdetxt();
            cargarDatos();
                                                      
        }catch(Exception ex)
        {
        
        }
                         
    }
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        HabilitarControles(true);
        HabilitarBotones(false);
        limpiar();
        int codigo = new Paciente().TraerNuevoCodigo();
        this.txtCodigo.setText(String.valueOf(codigo));
        this.lstPaciente.setEnabled(false);
        this.txtNombres.requestFocus();
        esGrabar = true;
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        HabilitarControles(true);
        HabilitarBotones(false);
        this.lstPaciente.setEnabled(false);
        esGrabar = false;
    }//GEN-LAST:event_btnEditarActionPerformed
    private void mensaje(String msj){
        JOptionPane.showMessageDialog(null, msj);
    }
    private void mensajeConfirmacion(String msj){
    
    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      int respuesta =  JOptionPane.showConfirmDialog(null, "¿Realmente desea eliminar el registro?", "Confirmar Salida",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       //SConsideara respuesta YES o SI - > 0 : NO o No -> 1 , si cierra la venta trae - 1
                if(respuesta == 1){
                    mensaje("Usuario selecciona opcion NO");
                }else if(respuesta == -1 ){
                    mensaje("Usuario selecciona opcion Cerrar");
                }else if(respuesta == 0){
                    mensaje("Usuario selecciona opcion SI");
                }


    }//GEN-LAST:event_btnEliminarActionPerformed
    private boolean Validar(){
    return true;
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (!Validar()) {
            return;
        }
        p = new Paciente();
        
        p.setCodigo(Integer.parseInt(this.txtCodigo.getText()));
        p.setNombres(txtNombres.getText());
        p.setApelidos(txtApellidos.getText());
        p.setDni(txtDni.getText());
        p.setTelefono(txtTelefono.getText());
        
        if(esGrabar){
             p.Insertar(p);
        }else{
            p.Actualizar(p);
        }
        Exportarfichero();
        actualizargrilla();
        HabilitarControles(false);
        HabilitarBotones(true);
        limpiar();
        this.lstPaciente.setEnabled(true);
        esGrabar = false;

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void Exportarfichero(){
         FileWriter fw = null;
        PrintWriter pw = null;
        try{
         fw = new FileWriter("C:\\Users\\IVAN\\Documents\\NetBeansProjects\\Program\\src\\BD\\Pacientes.txt");                  
          pw = new PrintWriter(fw);
          
         for(int x = 0 ; x < Paciente.lista.size(); x++){
             Paciente fila =  Paciente.lista.get(x);
       
             String linea = fila.getCodigo() + "|" + fila.getApelidos() + "|" + fila.getNombres() + "|"+  fila.getTelefono() + "|"+  fila.getDni();
        
              pw.println(linea);
         }
        }catch(Exception ex){
         ex.printStackTrace();
        }finally{
            try{
                if(fw != null){
                    fw.close();
                }
            }catch(Exception ex2){
                ex2.printStackTrace();
            }
         }
    }
    private void actualizargrilla(){
         //Observacion : LAS ARREGLOS   TIENE COMO SU INDICE BASE ES 0               
        String[] items = new String[Paciente.lista.size()];
        //mensaje(String.valueOf(Paciente.lista.size()));
        for(int i = 0 ; i < Paciente.lista.size(); i++ )
        {
            //mensaje("Captura de datos");
            String registro = Paciente.lista.get(i).getNombres() + " - " + Paciente.lista.get(i).getApelidos();
            //mensaje("Insercion al arreglo");
            items[i] = registro;
        }
        
         this.lstPaciente.setListData(items);
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        HabilitarControles(false);
        HabilitarBotones(true);
        limpiar();
        this.lstPaciente.setEnabled(true);
        esGrabar = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lstPacienteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPacienteValueChanged
        if(this.lstPaciente.getSelectedValue() != null){
            int indice = this.lstPaciente.getSelectedIndex();
        Paciente registro =  Paciente.lista.get(indice);
        this.txtCodigo.setText(String.valueOf(registro.getCodigo()));
        this.txtNombres.setText(registro.getNombres());
        this.txtApellidos.setText(registro.getApelidos());
        this.txtDni.setText(registro.getDni());
        this.txtTelefono.setText(registro.getTelefono());
        }
        
    }//GEN-LAST:event_lstPacienteValueChanged

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstPaciente;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
