/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital.GUI;

import Hospital.GUI.Mantenimientos.FrmCamas;
import Hospital.GUI.Mantenimientos.FrmEmpleado;
import Hospital.GUI.Mantenimientos.FrmMedicamento;
import Hospital.GUI.Mantenimientos.FrmPaciente;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;

/**
 *
 * @author IVAN
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    private BufferedImage img;
    public FrmPrincipal() {
        initComponents();
        try{
         this.setExtendedState( this.getExtendedState()|JFrame.MAXIMIZED_BOTH );
         img = ImageIO.read(new URL("C:/Users/IVAN/Documents/NetBeansProjects/Program/src/Hospital/Imagenes/Fondo.png"));
         jDesktopPane1 = new JDesktopPane(){
           
             protected void painComponet(Graphics grphs){
                  super.paintComponent(grphs);
                grphs.drawImage(img, 0, 0, null);
             }
             @Override
              public Dimension getPreferredSize() {
                return new Dimension(img.getWidth(), img.getHeight());
            }
         };
        }catch(Exception ex){
        
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMantenimientos = new javax.swing.JMenu();
        submenuEmpleado = new javax.swing.JMenuItem();
        submenuPaciente = new javax.swing.JMenuItem();
        submenuCamas = new javax.swing.JMenuItem();
        submenuMedicamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        menuMantenimientos.setText("Mantenimiento");

        submenuEmpleado.setText("Empleado");
        submenuEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuEmpleadoActionPerformed(evt);
            }
        });
        menuMantenimientos.add(submenuEmpleado);

        submenuPaciente.setText("Paciente");
        submenuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuPacienteActionPerformed(evt);
            }
        });
        menuMantenimientos.add(submenuPaciente);

        submenuCamas.setText("Camas");
        submenuCamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuCamasActionPerformed(evt);
            }
        });
        menuMantenimientos.add(submenuCamas);

        submenuMedicamento.setText("Medicamento");
        submenuMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenuMedicamentoActionPerformed(evt);
            }
        });
        menuMantenimientos.add(submenuMedicamento);

        jMenuBar1.add(menuMantenimientos);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submenuEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuEmpleadoActionPerformed
        FrmEmpleado f = new FrmEmpleado();
          jDesktopPane1.add(f);
        //aux.centrarIntenal(cat, jDesktopPane1);
        f .setVisible(true);
    }//GEN-LAST:event_submenuEmpleadoActionPerformed

    private void submenuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuPacienteActionPerformed
        FrmPaciente f = new FrmPaciente();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_submenuPacienteActionPerformed

    private void submenuCamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuCamasActionPerformed
        FrmCamas f = new FrmCamas();
        jDesktopPane1.add(f);
        f.setVisible(true);
        
    }//GEN-LAST:event_submenuCamasActionPerformed

    private void submenuMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuMedicamentoActionPerformed
        FrmMedicamento f = new FrmMedicamento();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_submenuMedicamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuMantenimientos;
    private javax.swing.JMenuItem submenuCamas;
    private javax.swing.JMenuItem submenuEmpleado;
    private javax.swing.JMenuItem submenuMedicamento;
    private javax.swing.JMenuItem submenuPaciente;
    // End of variables declaration//GEN-END:variables
}
